---
language: python
sudo: required
dist: xenial
services:
  - docker

python:
  - 3.8

matrix:
  fast_finish: true
  include:
    - { env: ANSIBLE=2.8 OS=ubuntu1604}
    - { env: ANSIBLE=2.9 OS=ubuntu1604}

    - { env: ANSIBLE=2.8 OS=ubuntu1804}
    - { env: ANSIBLE=2.9 OS=ubuntu1804}

    - { env: ANSIBLE=2.8 OS=centos7}
    - { env: ANSIBLE=2.9 OS=centos7}

    - { env: ANSIBLE=2.8 OS=centos8}
    - { env: ANSIBLE=2.9 OS=centos8}


before_install:
  - sudo apt-get -qq update
install:
  - pip install tox-travis
  - pip install docker-py
  - pip install molecule
script:
  - tox
